export const countries = [
  {
    name: 'Afghanistan',
    alpha2: 'AF',
    dialCode: '93',
    alpha3: 'AFG',
    capital: 'Kabul',
    score: '5',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Albania',
    alpha2: 'AL',
    dialCode: '355',
    alpha3: 'ALB',
    capital: 'Tirana',
    score: '2',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Algeria',
    alpha2: 'DZ',
    dialCode: '213',
    alpha3: 'DZA',
    capital: 'Algiers',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'American Samoa',
    alpha2: 'AS',
    dialCode: '1 684',
    alpha3: 'ASM',
    capital: 'Pago Pago',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Andorra',
    alpha2: 'AD',
    dialCode: '376',
    alpha3: 'AND',
    capital: 'Andorra la Vella',
    score: '',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Angola',
    alpha2: 'AO',
    dialCode: '244',
    alpha3: 'AGO',
    capital: 'Luanda',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Anguilla',
    alpha2: 'AI',
    dialCode: '1 264',
    alpha3: 'AIA',
    capital: 'The Valley',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Antigua and Barbuda',
    alpha2: 'AG',
    dialCode: '1268',
    alpha3: 'ATG',
    capital: "Saint John's",
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Argentina',
    alpha2: 'AR',
    dialCode: '54',
    alpha3: 'ARG',
    capital: 'Buenos Aires',
    score: '4',
    acquirer: '',
    continent: 'South America',
    paymentMethods: ['Visa', 'MasterCard', 'American Express', 'PayPal'],
  },
  {
    name: 'Armenia',
    alpha2: 'AM',
    dialCode: '374',
    alpha3: 'ARM',
    capital: 'Yerevan',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Aruba',
    alpha2: 'AW',
    dialCode: '297',
    alpha3: 'ABW',
    capital: 'Oranjestad',
    score: '',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'Australia',
    alpha2: 'AU',
    dialCode: '61',
    alpha3: 'AUS',
    capital: 'Canberra',
    score: '1',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Austria',
    alpha2: 'AT',
    dialCode: '43',
    alpha3: 'AUT',
    capital: 'Vienna',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'Azerbaijan',
    alpha2: 'AZ',
    dialCode: '994',
    alpha3: 'AZE',
    capital: 'Baku',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: ['MasterCard'],
  },
  {
    name: 'Bahamas',
    alpha2: 'BS',
    dialCode: '1 242',
    alpha3: 'BHS',
    capital: 'Nassau',
    score: '2',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Bahrain',
    alpha2: 'BH',
    dialCode: '973',
    alpha3: 'BHR',
    capital: 'Manama',
    score: '3',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: ['Visa', 'MasterCard', 'PayPal'],
  },
  {
    name: 'Bangladesh',
    alpha2: 'BD',
    dialCode: '880',
    alpha3: 'BGD',
    capital: 'Dhaka',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Barbados',
    alpha2: 'BB',
    dialCode: '1 246',
    alpha3: 'BRB',
    capital: 'Bridgetown',
    score: '3',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Belarus',
    alpha2: 'BY',
    dialCode: '375',
    alpha3: 'BLR',
    capital: 'Minsk',
    score: '4',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Belgium',
    alpha2: 'BE',
    dialCode: '32',
    alpha3: 'BEL',
    capital: 'Brussels',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Belize',
    alpha2: 'BZ',
    dialCode: '501',
    alpha3: 'BLZ',
    capital: 'Belmopan',
    score: '3',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Benin',
    alpha2: 'BJ',
    dialCode: '229',
    alpha3: 'BEN',
    capital: 'Porto-Novo',
    score: '2',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Bermuda',
    alpha2: 'BM',
    dialCode: '1 441',
    alpha3: 'BMU',
    capital: 'Hamilton',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Bhutan',
    alpha2: 'BT',
    dialCode: '975',
    alpha3: 'BTN',
    capital: 'Thimphu',
    score: '',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Bolivia',
    alpha2: 'BO',
    dialCode: '591',
    alpha3: 'BOL',
    capital: 'Sucre',
    score: '4',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2: 'BA',
    dialCode: '387',
    alpha3: 'BIH',
    capital: 'Sarajevo',
    score: '3',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Botswana',
    alpha2: 'BW',
    dialCode: '267',
    alpha3: 'BWA',
    capital: 'Gaborone',
    score: '2',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Brazil',
    alpha2: 'BR',
    dialCode: '55',
    alpha3: 'BRA',
    capital: 'Brasília',
    score: '2',
    acquirer: '',
    continent: 'South America',
    paymentMethods: ['American Express', 'Diners'],
  },
  {
    name: 'British Indian Ocean Territory',
    alpha2: 'IO',
    dialCode: '246',
    alpha3: 'IOT',
    capital: 'Diego Garcia',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Brunei Darussalam',
    alpha2: 'BN',
    dialCode: '673',
    alpha3: 'BRN',
    capital: 'Bandar Seri Begawan',
    score: '',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Bulgaria',
    alpha2: 'BG',
    dialCode: '359',
    alpha3: 'BGR',
    capital: 'Sofia',
    score: '2',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Burkina Faso',
    alpha2: 'BF',
    dialCode: '226',
    alpha3: 'BFA',
    capital: 'Ouagadougou',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Burundi',
    alpha2: 'BI',
    dialCode: '257',
    alpha3: 'BDI',
    capital: 'Bujumbura',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Cambodia',
    alpha2: 'KH',
    dialCode: '855',
    alpha3: 'KHM',
    capital: 'Phnom Penh',
    score: '3',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Cameroon',
    alpha2: 'CM',
    dialCode: '237',
    alpha3: 'CMR',
    capital: 'Yaoundé',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Canada',
    alpha2: 'CA',
    dialCode: '1',
    alpha3: 'CAN',
    capital: 'Ottawa',
    score: '1',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Cape Verde',
    alpha2: 'CV',
    dialCode: '238',
    alpha3: 'CPV',
    capital: 'Praia',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Cayman Islands',
    alpha2: 'KY',
    dialCode: ' 345',
    alpha3: 'CYM',
    capital: 'George Town',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Central African Republic',
    alpha2: 'CF',
    dialCode: '236',
    alpha3: 'CAF',
    capital: 'Bangui',
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Chad',
    alpha2: 'TD',
    dialCode: '235',
    alpha3: 'TCD',
    capital: "N'Djamena",
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Chile',
    alpha2: 'CL',
    dialCode: '56',
    alpha3: 'CHL',
    capital: 'Santiago',
    score: '1',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'Diners',
      'PayPal',
    ],
  },
  {
    name: 'China',
    alpha2: 'CN',
    dialCode: '86',
    alpha3: 'CHN',
    capital: 'Beijing',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'Union Pay',
      'JCB',
      'PayPal',
    ],
  },
  {
    name: 'Christmas Island',
    alpha2: 'CX',
    dialCode: '61',
    alpha3: 'CXR',
    capital: 'Flying Fish Cove',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Cocos (Keeling) Islands',
    alpha2: 'CC',
    dialCode: '61',
    alpha3: 'CCK',
    capital: 'West Island',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Colombia',
    alpha2: 'CO',
    dialCode: '57',
    alpha3: 'COL',
    capital: 'Bogotá',
    score: '3',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'Diners',
      'PayPal',
    ],
  },
  {
    name: 'Comoros',
    alpha2: 'KM',
    dialCode: '269',
    alpha3: 'COM',
    capital: 'Moroni',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Democratic Republic of Congo',
    alpha2: 'CD',
    dialCode: '243',
    alpha3: 'COD',
    capital: 'Kinshasa',
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Republic of Congo',
    alpha2: 'CG',
    dialCode: '242',
    alpha3: 'COG',
    capital: 'Brazzaville',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Cook Islands',
    alpha2: 'CK',
    dialCode: '682',
    alpha3: 'COK',
    capital: 'Avarua',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Costa Rica',
    alpha2: 'CR',
    dialCode: '506',
    alpha3: 'CRI',
    capital: 'San José',
    score: '1',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Croatia',
    alpha2: 'HR',
    dialCode: '385',
    alpha3: 'HRV',
    capital: 'Zagreb',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Cuba',
    alpha2: 'CU',
    dialCode: '53',
    alpha3: 'CUB',
    capital: 'Havana',
    score: '5',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Curaçao',
    alpha2: 'CW',
    dialCode: '',
    alpha3: 'CUW',
    capital: 'Willemstad',
    score: '',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'Cyprus',
    alpha2: 'CY',
    dialCode: '537',
    alpha3: 'CYP',
    capital: 'Nicosia',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'PayPal',
    ],
  },
  {
    name: 'Czech Republic',
    alpha2: 'CZ',
    dialCode: '420',
    alpha3: 'CZE',
    capital: 'Prague',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: "Côte D'Ivoire",
    alpha2: 'CI',
    dialCode: '225',
    alpha3: 'CIV',
    capital: 'Yamoussoukro',
    score: '2',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Denmark',
    alpha2: 'DK',
    dialCode: '45',
    alpha3: 'DNK',
    capital: 'Copenhagen',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'Djibouti',
    alpha2: 'DJ',
    dialCode: '253',
    alpha3: 'DJI',
    capital: 'Djibouti',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Dominica',
    alpha2: 'DM',
    dialCode: '1 767',
    alpha3: 'DMA',
    capital: 'Roseau',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Dominican Republic',
    alpha2: 'DO',
    dialCode: '1 849',
    alpha3: 'DOM',
    capital: 'Santo Domingo',
    score: '2',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Ecuador',
    alpha2: 'EC',
    dialCode: '593',
    alpha3: 'ECU',
    capital: 'Quito',
    score: '4',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'Egypt',
    alpha2: 'EG',
    dialCode: '20',
    alpha3: 'EGY',
    capital: 'Cairo',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'El Salvador',
    alpha2: 'SV',
    dialCode: '503',
    alpha3: 'SLV',
    capital: 'San Salvador',
    score: '4',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Equatorial Guinea',
    alpha2: 'GQ',
    dialCode: '240',
    alpha3: 'GNQ',
    capital: 'Malabo',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Eritrea',
    alpha2: 'ER',
    dialCode: '291',
    alpha3: 'ERI',
    capital: 'Asmara',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Estonia',
    alpha2: 'EE',
    dialCode: '372',
    alpha3: 'EST',
    capital: 'Tallinn',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'Ethiopia',
    alpha2: 'ET',
    dialCode: '251',
    alpha3: 'ETH',
    capital: 'Addis Ababa',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Falkland Islands',
    alpha2: 'FK',
    dialCode: '500',
    alpha3: 'FLK',
    capital: 'Stanley',
    score: '',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'Faroe Islands',
    alpha2: 'FO',
    dialCode: '298',
    alpha3: 'FRO',
    capital: 'Tórshavn',
    score: '',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Fiji',
    alpha2: 'FJ',
    dialCode: '679',
    alpha3: 'FJI',
    capital: 'Suva',
    score: '3',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Finland',
    alpha2: 'FI',
    dialCode: '358',
    alpha3: 'FIN',
    capital: 'Helsinki',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'France',
    alpha2: 'FR',
    dialCode: '33',
    alpha3: 'FRA',
    capital: 'Paris',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'French Guiana',
    alpha2: 'GF',
    dialCode: '594',
    alpha3: 'GUF',
    capital: 'Cayenne',
    score: '',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'French Polynesia',
    alpha2: 'PF',
    dialCode: '689',
    alpha3: 'PYF',
    capital: 'Papeetē',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'French Southern Territories',
    alpha2: 'TF',
    dialCode: '',
    alpha3: 'ATF',
    capital: 'Port-aux-Français',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Gabon',
    alpha2: 'GA',
    dialCode: '241',
    alpha3: 'GAB',
    capital: 'Libreville',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Gambia',
    alpha2: 'GM',
    dialCode: '220',
    alpha3: 'GMB',
    capital: 'Banjul',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Georgia',
    alpha2: 'GE',
    dialCode: '995',
    alpha3: 'GEO',
    capital: 'Tbilisi',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Germany',
    alpha2: 'DE',
    dialCode: '49',
    alpha3: 'DEU',
    capital: 'Berlin',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'Ghana',
    alpha2: 'GH',
    dialCode: '233',
    alpha3: 'GHA',
    capital: 'Accra',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Gibraltar',
    alpha2: 'GI',
    dialCode: '350',
    alpha3: 'GIB',
    capital: 'Gibraltar',
    score: '1',
    acquirer: 'PXP',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Greece',
    alpha2: 'GR',
    dialCode: '30',
    alpha3: 'GRC',
    capital: 'Athens',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Greenland',
    alpha2: 'GL',
    dialCode: '299',
    alpha3: 'GRL',
    capital: 'Nuuk',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Grenada',
    alpha2: 'GD',
    dialCode: '1 473',
    alpha3: 'GRD',
    capital: "St. George's",
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Guadeloupe',
    alpha2: 'GP',
    dialCode: '590',
    alpha3: 'GLP',
    capital: 'Basse-Terre',
    score: '1',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Guam',
    alpha2: 'GU',
    dialCode: '1 671',
    alpha3: 'GUM',
    capital: 'Hagåtña',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Guatemala',
    alpha2: 'GT',
    dialCode: '502',
    alpha3: 'GTM',
    capital: 'Guatemala City',
    score: '3',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Guernsey',
    alpha2: 'GG',
    dialCode: '44',
    alpha3: 'GGY',
    capital: 'St. Peter Port',
    score: '',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Guinea',
    alpha2: 'GN',
    dialCode: '224',
    alpha3: 'GIN',
    capital: 'Conakry',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Guinea-Bissau',
    alpha2: 'GW',
    dialCode: '245',
    alpha3: 'GNB',
    capital: 'Bissau',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Guyana',
    alpha2: 'GY',
    dialCode: '595',
    alpha3: 'GUY',
    capital: 'Georgetown',
    score: '2',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'Haiti',
    alpha2: 'HT',
    dialCode: '509',
    alpha3: 'HTI',
    capital: 'Port-au-Prince',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Heard Island and Mcdonald Islands',
    alpha2: 'HM',
    dialCode: '',
    alpha3: 'HMD',
    capital: '',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Honduras',
    alpha2: 'HN',
    dialCode: '504',
    alpha3: 'HND',
    capital: 'Tegucigalpa',
    score: '3',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Hong Kong',
    alpha2: 'HK',
    dialCode: '852',
    alpha3: 'HKG',
    capital: 'City of Victoria',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Hungary',
    alpha2: 'HU',
    dialCode: '36',
    alpha3: 'HUN',
    capital: 'Budapest',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Iceland',
    alpha2: 'IS',
    dialCode: '354',
    alpha3: 'ISL',
    capital: 'Reykjavik',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'India',
    alpha2: 'IN',
    dialCode: '91',
    alpha3: 'IND',
    capital: 'New Delhi',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Indonesia',
    alpha2: 'ID',
    dialCode: '62',
    alpha3: 'IDN',
    capital: 'Jakarta',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'JCB',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Iran',
    alpha2: 'IR',
    dialCode: '98',
    alpha3: 'IRN',
    capital: 'Tehran',
    score: '5',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Iraq',
    alpha2: 'IQ',
    dialCode: '964',
    alpha3: 'IRQ',
    capital: 'Baghdad',
    score: '5',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Ireland',
    alpha2: 'IE',
    dialCode: '353',
    alpha3: 'IRL',
    capital: 'Dublin',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Isle of Man',
    alpha2: 'IM',
    dialCode: '44',
    alpha3: 'IMN',
    capital: 'Douglas',
    score: '1',
    acquirer: 'PXP',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Israel',
    alpha2: 'IL',
    dialCode: '972',
    alpha3: 'ISR',
    capital: 'Jerusalem',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Italy',
    alpha2: 'IT',
    dialCode: '39',
    alpha3: 'ITA',
    capital: 'Rome',
    ISO: 'IT',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Jamaica',
    alpha2: 'JM',
    dialCode: '1 876',
    alpha3: 'JAM',
    capital: 'Kingston',
    score: '3',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Japan',
    alpha2: 'JP',
    dialCode: '81',
    alpha3: 'JPN',
    capital: 'Tokyo',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'JCB',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Jersey',
    alpha2: 'JE',
    dialCode: '44',
    alpha3: 'JEY',
    capital: 'Saint Helier',
    score: '1',
    acquirer: 'PXP',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },

  {
    name: 'Jordan',
    alpha2: 'JO',
    dialCode: '962',
    alpha3: 'JOR',
    capital: 'Amman',
    score: '3',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'American Express',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Kazakhstan',
    alpha2: 'KZ',
    dialCode: '77',
    alpha3: 'KAZ',
    capital: 'Astana',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Kenya',
    alpha2: 'KE',
    dialCode: '254',
    alpha3: 'KEN',
    capital: 'Nairobi',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Kiribati',
    alpha2: 'KI',
    dialCode: '686',
    alpha3: 'KIR',
    capital: 'South Tarawa',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Kosovo',
    alpha2: 'XK',
    dialCode: '383',
    alpha3: '',
    capital: 'Pristina',
    score: '',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Kuwait',
    alpha2: 'KW',
    dialCode: '965',
    alpha3: 'KWT',
    capital: 'Kuwait City',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: ['Visa', 'MasterCard', 'PayPal'],
  },
  {
    name: 'Kyrgyzstan',
    alpha2: 'KG',
    dialCode: '996',
    alpha3: 'KGZ',
    capital: 'Bishkek',
    score: '3',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: "Lao People's Democratic Republic",
    alpha2: 'LA',
    dialCode: '856',
    alpha3: 'LAO',
    capital: 'Vientiane',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Latvia',
    alpha2: 'LV',
    dialCode: '371',
    alpha3: 'LVA',
    capital: 'Riga',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'Lebanon',
    alpha2: 'LB',
    dialCode: '961',
    alpha3: 'LBN',
    capital: 'Beirut',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Lesotho',
    alpha2: 'LS',
    dialCode: '266',
    alpha3: 'LSO',
    capital: 'Maseru',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Liberia',
    alpha2: 'LR',
    dialCode: '231',
    alpha3: 'LBR',
    capital: 'Monrovia',
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Libya',
    alpha2: 'LY',
    dialCode: '218',
    alpha3: 'LBY',
    capital: 'Tripoli',
    score: '5',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Liechtenstein',
    alpha2: 'LI',
    dialCode: '423',
    alpha3: 'LIE',
    capital: 'Vaduz',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Lithuania',
    alpha2: 'LT',
    dialCode: '370',
    alpha3: 'LTU',
    capital: 'Vilnius',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'Luxembourg',
    alpha2: 'LU',
    dialCode: '352',
    alpha3: 'LUX',
    capital: 'Luxembourg',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Macao',
    alpha2: 'MO',
    dialCode: '853',
    alpha3: 'MAC',
    capital: '',
    score: '',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Macedonia',
    alpha2: 'MK',
    dialCode: '389',
    alpha3: 'MKD',
    capital: 'Skopje',
    score: '3',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Madagascar',
    alpha2: 'MG',
    dialCode: '261',
    alpha3: 'MDG',
    capital: 'Antananarivo',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Malawi',
    alpha2: 'MW',
    dialCode: '265',
    alpha3: 'MWI',
    capital: 'Lilongwe',
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: ['Visa', 'MasterCard', 'JCB', 'Discover', 'PayPal'],
  },
  {
    name: 'Malaysia',
    alpha2: 'MY',
    dialCode: '60',
    alpha3: 'MYS',
    capital: 'Kuala Lumpur',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'JCB',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Maldives',
    alpha2: 'MV',
    dialCode: '960',
    alpha3: 'MDV',
    capital: 'Malé',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Mali',
    alpha2: 'ML',
    dialCode: '223',
    alpha3: 'MLI',
    capital: 'Bamako',
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Malta',
    alpha2: 'MT',
    dialCode: '356',
    alpha3: 'MLT',
    capital: 'Valletta',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Marshall Islands',
    alpha2: 'MH',
    dialCode: '692',
    alpha3: 'MHL',
    capital: 'Majuro',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Martinique',
    alpha2: 'MQ',
    dialCode: '596',
    alpha3: 'MTQ',
    capital: 'Fort-de-France',
    score: '1',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Mauritania',
    alpha2: 'MR',
    dialCode: '222',
    alpha3: 'MRT',
    capital: 'Nouakchott',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Mauritius',
    alpha2: 'MU',
    dialCode: '230',
    alpha3: 'MUS',
    capital: 'Port Louis',
    score: '1',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: ['Visa', 'MasterCard', 'American Express', 'PayPal'],
  },
  {
    name: 'Mayotte',
    alpha2: 'YT',
    dialCode: '262',
    alpha3: 'MYT',
    capital: 'Mamoudzou',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Mexico',
    alpha2: 'MX',
    dialCode: '52',
    alpha3: 'MEX',
    capital: 'Mexico City',
    score: '2',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'PayPal',
    ],
  },
  {
    name: 'Micronesia',
    alpha2: 'FM',
    dialCode: '691',
    alpha3: 'FSM',
    capital: 'Palikir',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Moldova',
    alpha2: 'MD',
    dialCode: '373',
    alpha3: 'MDA',
    capital: 'Chișinău',
    score: '3',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Monaco',
    alpha2: 'MC',
    dialCode: '377',
    alpha3: 'MCO',
    capital: 'Monaco',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Mongolia',
    alpha2: 'MN',
    dialCode: '976',
    alpha3: 'MNG',
    capital: 'Ulan Bator',
    score: '3',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Montenegro',
    alpha2: 'ME',
    dialCode: '382',
    alpha3: 'MNE',
    capital: 'Podgorica',
    score: '3',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Montserrat',
    alpha2: 'MS',
    dialCode: '1664',
    alpha3: 'MSR',
    capital: 'Plymouth',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Morocco',
    alpha2: 'MA',
    dialCode: '212',
    alpha3: 'MAR',
    capital: 'Rabat',
    score: '2',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Mozambique',
    alpha2: 'MZ',
    dialCode: '258',
    alpha3: 'MOZ',
    capital: 'Maputo',
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: ['Visa', 'MasterCard', 'JCB', 'Discover', 'PayPal'],
  },
  {
    name: 'Myanmar',
    alpha2: 'MM',
    dialCode: '95',
    alpha3: 'MMR',
    capital: 'Naypyidaw',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Namibia',
    alpha2: 'NA',
    dialCode: '264',
    alpha3: 'NAM',
    capital: 'Windhoek',
    score: '2',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Nauru',
    alpha2: 'NR',
    dialCode: '674',
    alpha3: 'NRU',
    capital: 'Yaren',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Nepal',
    alpha2: 'NP',
    dialCode: '977',
    alpha3: 'NPL',
    capital: 'Kathmandu',
    score: '3',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Netherlands',
    alpha2: 'NL',
    dialCode: '31',
    alpha3: 'NLD',
    capital: 'Amsterdam',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'Ideal',
      'PayPal',
    ],
  },
  {
    name: 'New Caledonia',
    alpha2: 'NC',
    dialCode: '687',
    alpha3: 'NCL',
    capital: 'Nouméa',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'New Zealand',
    alpha2: 'NZ',
    dialCode: '64',
    alpha3: 'NZL',
    capital: 'Wellington',
    score: '1',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Nicaragua',
    alpha2: 'NI',
    dialCode: '505',
    alpha3: 'NIC',
    capital: 'Managua',
    score: '4',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Niger',
    alpha2: 'NE',
    dialCode: '227',
    alpha3: 'NER',
    capital: 'Niamey',
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Nigeria',
    alpha2: 'NG',
    dialCode: '234',
    alpha3: 'NGA',
    capital: 'Abuja',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Niue',
    alpha2: 'NU',
    dialCode: '683',
    alpha3: 'NIU',
    capital: 'Alofi',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Norfolk Island',
    alpha2: 'NF',
    dialCode: '672',
    alpha3: 'NFK',
    capital: 'Kingston',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'North Korea',
    alpha2: 'KP',
    dialCode: '850',
    alpha3: 'PRK',
    capital: 'Pyongyang',
    score: '5',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Northern Mariana Islands',
    alpha2: 'MP',
    dialCode: '1 670',
    alpha3: 'MNP',
    capital: 'Saipan',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Norway',
    alpha2: 'NO',
    dialCode: '47',
    alpha3: 'NOR',
    capital: 'Oslo',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'Oman',
    alpha2: 'OM',
    dialCode: '968',
    alpha3: 'OMN',
    capital: 'Muscat',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Pakistan',
    alpha2: 'PK',
    dialCode: '92',
    alpha3: 'PAK',
    capital: 'Islamabad',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Palau',
    alpha2: 'PW',
    dialCode: '680',
    alpha3: 'PLW',
    capital: 'Ngerulmud',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Palestinian Territory',
    alpha2: 'PS',
    dialCode: '970',
    alpha3: 'PSE',
    capital: 'Ramallah',
    score: '',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Panama',
    alpha2: 'PA',
    dialCode: '507',
    alpha3: 'PAN',
    capital: 'Panama City',
    score: '2',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Papua New Guinea',
    alpha2: 'PG',
    dialCode: '675',
    alpha3: 'PNG',
    capital: 'Port Moresby',
    score: '2',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Paraguay',
    alpha2: 'PY',
    dialCode: '595',
    alpha3: 'PRY',
    capital: 'Asunción',
    score: '2',
    acquirer: '',
    continent: 'South America',
    paymentMethods: ['Diners', 'Discover'],
  },
  {
    name: 'Peru',
    alpha2: 'PE',
    dialCode: '51',
    alpha3: 'PER',
    capital: 'Lima',
    score: '2',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'Diners',
      'PayPal',
    ],
  },
  {
    name: 'Philippines',
    alpha2: 'PH',
    dialCode: '63',
    alpha3: 'PHL',
    capital: 'Manila',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'JCB',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Pitcairn Islands',
    alpha2: 'PN',
    dialCode: '872',
    alpha3: 'PCN',
    capital: 'Adamstown',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Poland',
    alpha2: 'PL',
    dialCode: '48',
    alpha3: 'POL',
    capital: 'Warsaw',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Przelewy24',
      'PayPal',
    ],
  },
  {
    name: 'Portugal',
    alpha2: 'PT',
    dialCode: '351',
    alpha3: 'PRT',
    capital: 'Lisbon',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Puerto Rico',
    alpha2: 'PR',
    dialCode: '1 939',
    alpha3: 'PRI',
    capital: 'San Juan',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Qatar',
    alpha2: 'QA',
    dialCode: '974',
    alpha3: 'QAT',
    capital: 'Doha',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Romania',
    alpha2: 'RO',
    dialCode: '40',
    alpha3: 'ROU',
    capital: 'Bucharest',
    score: '2',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Russia',
    alpha2: 'RU',
    dialCode: '7',
    alpha3: 'RUS',
    capital: 'Moscow',
    score: '4',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Rwanda',
    alpha2: 'RW',
    dialCode: '250',
    alpha3: 'RWA',
    capital: 'Kigali',
    score: '1',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Réunion',
    alpha2: 'RE',
    dialCode: '262',
    alpha3: 'REU',
    capital: 'Saint-Denis',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Saint Barthélemy',
    alpha2: 'BL',
    dialCode: '590',
    alpha3: 'BLM',
    capital: 'Gustavia',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Saint Helena',
    alpha2: 'SH',
    dialCode: '290',
    alpha3: 'SHN',
    capital: '',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Saint Kitts and Nevis',
    alpha2: 'KN',
    dialCode: '1 869',
    alpha3: 'KNA',
    capital: 'Basseterre',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Saint Lucia',
    alpha2: 'LC',
    dialCode: '1 758',
    alpha3: 'LCA',
    capital: 'Castries',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Saint Martin (French Part)',
    alpha2: 'MF',
    dialCode: '590',
    alpha3: 'MAF',
    capital: 'Marigot',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Saint Pierre and Miquelon',
    alpha2: 'PM',
    dialCode: '508',
    alpha3: 'SPM',
    capital: 'Saint-Pierre',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Saint Vincent and The Grenadines',
    alpha2: 'VC',
    dialCode: '1 784',
    alpha3: 'VCT',
    capital: 'Kingstown',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Samoa',
    alpha2: 'WS',
    dialCode: '685',
    alpha3: 'WSM',
    capital: 'Apia',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'San Marino',
    alpha2: 'SM',
    dialCode: '378',
    alpha3: 'SMR',
    capital: 'City of San Marino',
    score: '',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Sao Tome and Principe',
    alpha2: 'ST',
    dialCode: '239',
    alpha3: 'STP',
    capital: 'São Tomé',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Saudi Arabia',
    alpha2: 'SA',
    dialCode: '966',
    alpha3: 'SAU',
    capital: 'Riyadh',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Senegal',
    alpha2: 'SN',
    dialCode: '221',
    alpha3: 'SEN',
    capital: 'Dakar',
    score: '2',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Serbia',
    alpha2: 'RS',
    dialCode: '381',
    alpha3: 'SRB',
    capital: 'Belgrade',
    score: '3',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Seychelles',
    alpha2: 'SC',
    dialCode: '248',
    alpha3: 'SYC',
    capital: 'Victoria',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Sierra Leone',
    alpha2: 'SL',
    dialCode: '232',
    alpha3: 'SLE',
    capital: 'Freetown',
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Singapore',
    alpha2: 'SG',
    dialCode: '65',
    alpha3: 'SGP',
    capital: 'Singapore',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'JCB',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Saint Maarten',
    alpha2: 'SX',
    dialCode: '',
    alpha3: 'SXM',
    capital: 'Philipsburg',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Slovakia',
    alpha2: 'SK',
    dialCode: '421',
    alpha3: 'SVK',
    capital: 'Bratislava',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Slovenia',
    alpha2: 'SI',
    dialCode: '386',
    alpha3: 'SVN',
    capital: 'Ljubljana',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Solomon Islands',
    alpha2: 'SB',
    dialCode: '677',
    alpha3: 'SLB',
    capital: 'Honiara',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Somalia',
    alpha2: 'SO',
    dialCode: '252',
    alpha3: 'SOM',
    capital: 'Mogadishu',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'South Africa',
    alpha2: 'ZA',
    dialCode: '27',
    alpha3: 'ZAF',
    capital: 'Pretoria',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'South Georgia',
    alpha2: 'GS',
    dialCode: '500',
    alpha3: 'SGS',
    capital: 'King Edward Point',
    score: '',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'South Korea',
    alpha2: 'KR',
    dialCode: '82',
    alpha3: 'KOR',
    capital: 'Seoul',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'South Sudan',
    alpha2: 'SS',
    dialCode: '',
    alpha3: 'SSD',
    capital: 'Juba',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Spain',
    alpha2: 'ES',
    dialCode: '34',
    alpha3: 'ESP',
    capital: 'Madrid',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'Sri Lanka',
    alpha2: 'LK',
    dialCode: '94',
    alpha3: 'LKA',
    capital: 'Colombo',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Sudan',
    alpha2: 'SD',
    dialCode: '249',
    alpha3: 'SDN',
    capital: 'Khartoum',
    score: '5',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Suriname',
    alpha2: 'SR',
    dialCode: '597',
    alpha3: 'SUR',
    capital: 'Paramaribo',
    score: '4',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'Svalbard and Jan Mayen',
    alpha2: 'SJ',
    dialCode: '47',
    alpha3: 'SJM',
    capital: 'Longyearbyen',
    score: '',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Swaziland',
    alpha2: 'SZ',
    dialCode: '268',
    alpha3: 'SWZ',
    capital: 'Lobamba',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Sweden',
    alpha2: 'SE',
    dialCode: '46',
    alpha3: 'SWE',
    capital: 'Stockholm',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'Switzerland',
    alpha2: 'CH',
    dialCode: '41',
    alpha3: 'CHE',
    capital: 'Bern',
    score: '1',
    acquirer: 'Ryvyl EU',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Syrian Arab Republic',
    alpha2: 'SY',
    dialCode: '963',
    alpha3: 'SYR',
    capital: 'Damascus',
    score: '',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Taiwan',
    alpha2: 'TW',
    dialCode: '886',
    alpha3: 'TWN',
    capital: 'Taipei',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
      'Mada',
    ],
  },
  {
    name: 'Tajikistan',
    alpha2: 'TJ',
    dialCode: '992',
    alpha3: 'TJK',
    capital: 'Dushanbe',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Tanzania',
    alpha2: 'TZ',
    dialCode: '255',
    alpha3: 'TZA',
    capital: 'Dodoma',
    score: '2',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Thailand',
    alpha2: 'TH',
    dialCode: '66',
    alpha3: 'THA',
    capital: 'Bangkok',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Timor-Leste',
    alpha2: 'TL',
    dialCode: '670',
    alpha3: 'TLS',
    capital: 'Dili',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Togo',
    alpha2: 'TG',
    dialCode: '228',
    alpha3: 'TGO',
    capital: 'Lomé',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Tokelau',
    alpha2: 'TK',
    dialCode: '690',
    alpha3: 'TKL',
    capital: 'Fakaofo',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Tonga',
    alpha2: 'TO',
    dialCode: '676',
    alpha3: 'TON',
    capital: "Nuku'alofa",
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Trinidad and Tobago',
    alpha2: 'TT',
    dialCode: '1 868',
    alpha3: 'TTO',
    capital: 'Port of Spain',
    score: '2',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Tunisia',
    alpha2: 'TN',
    dialCode: '216',
    alpha3: 'TUN',
    capital: 'Tunis',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Turkey',
    alpha2: 'TR',
    dialCode: '90',
    alpha3: 'TUR',
    capital: 'Ankara',
    score: '3',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Diner',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Turkmenistan',
    alpha2: 'TM',
    dialCode: '993',
    alpha3: 'TKM',
    capital: 'Ashgabat',
    score: '4',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Turks and Caicos Islands',
    alpha2: 'TC',
    dialCode: '1 649',
    alpha3: 'TCA',
    capital: 'Cockburn Town',
    score: '4',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Tuvalu',
    alpha2: 'TV',
    dialCode: '688',
    alpha3: 'TUV',
    capital: 'Funafuti',
    score: '4',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Uganda',
    alpha2: 'UG',
    dialCode: '256',
    alpha3: 'UGA',
    capital: 'Kampala',
    score: '3',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Ukraine',
    alpha2: 'UA',
    dialCode: '380',
    alpha3: 'UKR',
    capital: 'Kyiv',
    score: '4',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'United Arab Emirates',
    alpha2: 'AE',
    dialCode: '971',
    alpha3: 'ARE',
    capital: 'Abu Dhabi',
    score: '1',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'United Kingdom',
    alpha2: 'GB',
    dialCode: '44',
    alpha3: 'GBR',
    capital: 'London',
    score: '1',
    acquirer: 'PXP',
    continent: 'Europe',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'Union Pay',
      'JCB',
      'Diners',
      'Discover',
      'Trustly',
      'PayPal',
    ],
  },
  {
    name: 'United States',
    alpha2: 'US',
    dialCode: '1',
    alpha3: 'USA',
    capital: 'Washington D.C.',
    score: '1',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'Apple Pay',
      'Google Pay',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'United States Minor Outlying Islands',
    alpha2: 'UM',
    dialCode: '',
    alpha3: 'UMI',
    capital: '',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Uruguay',
    alpha2: 'UY',
    dialCode: '598',
    alpha3: 'URY',
    capital: 'Montevideo',
    score: '1',
    acquirer: '',
    continent: 'South America',
    paymentMethods: ['Diners'],
  },
  {
    name: 'Uzbekistan',
    alpha2: 'UZ',
    dialCode: '998',
    alpha3: 'UZB',
    capital: 'Tashkent',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Vanuatu',
    alpha2: 'VU',
    dialCode: '678',
    alpha3: 'VUT',
    capital: 'Port Vila',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Vatican City',
    alpha2: 'VA',
    dialCode: '379',
    alpha3: 'VAT',
    capital: 'Vatican City',
    score: '',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
  {
    name: 'Venezuela',
    alpha2: 'VE',
    dialCode: '58',
    alpha3: 'VEN',
    capital: 'Caracas',
    score: '5',
    acquirer: '',
    continent: 'South America',
    paymentMethods: [],
  },
  {
    name: 'Vietnam',
    alpha2: 'VN',
    dialCode: '84',
    alpha3: 'VNM',
    capital: 'Hanoi',
    score: '2',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [
      'Visa',
      'MasterCard',
      'American Express',
      'JCB',
      'Diners',
      'Discover',
      'PayPal',
    ],
  },
  {
    name: 'Virgin Islands, British',
    alpha2: 'VG',
    dialCode: '1 284',
    alpha3: 'VGB',
    capital: 'Road Town',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Virgin Islands, U.S.',
    alpha2: 'VI',
    dialCode: '1 340',
    alpha3: 'VIR',
    capital: 'Charlotte Amalie',
    score: '',
    acquirer: '',
    continent: 'North America',
    paymentMethods: [],
  },
  {
    name: 'Wallis and Futuna',
    alpha2: 'WF',
    dialCode: '681',
    alpha3: 'WLF',
    capital: 'Mata-Utu',
    score: '',
    acquirer: '',
    continent: 'Oceania',
    paymentMethods: [],
  },
  {
    name: 'Western Sahara',
    alpha2: 'EH',
    dialCode: '',
    alpha3: 'ESH',
    capital: 'El Aaiún',
    score: '',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Yemen',
    alpha2: 'YE',
    dialCode: '967',
    alpha3: 'YEM',
    capital: "Sana'a",
    score: '',
    acquirer: '',
    continent: 'Asia',
    paymentMethods: [],
  },
  {
    name: 'Zambia',
    alpha2: 'ZM',
    dialCode: '260',
    alpha3: 'ZMB',
    capital: 'Lusaka',
    score: '4',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Zimbabwe',
    alpha2: 'ZW',
    dialCode: '263',
    alpha3: 'ZWE',
    capital: 'Harare',
    score: '5',
    acquirer: '',
    continent: 'Africa',
    paymentMethods: [],
  },
  {
    name: 'Åland Islands',
    alpha2: 'AX',
    dialCode: '',
    alpha3: 'ALA',
    capital: 'Mariehamn',
    score: '',
    acquirer: '',
    continent: 'Europe',
    paymentMethods: [],
  },
]
