export const industries = [
  {
    label: 'Retail',
    items: [
      { label: 'Software', value: 'retail-software' },
      { label: 'Clothing and accessories', value: 'retail-clothing-and-accessories' },
      { label: 'Convenience stores', value: 'retail-convenience-stores' },
      { label: 'Beauty products', value: 'retail-beauty-products' },
      { label: 'Home goods and furniture', value: 'retail-home-goods-and-furniture' },
      { label: 'Home electronics', value: 'retail-home-electronics' },
      { label: 'Auto parts and accessories', value: 'retail-auto-parts-and-accessories' },
      { label: 'Jewellery stores, watches, clocks, and silverware', value: 'retail-jewellery-stores-watches-clocks-and-silverware' },
      { label: 'Precious stones and metals, watches and jewellery', value: 'retail-precious-stones-and-metals-watches-and-jewellery' },
      { label: 'Other merchandise', value: 'retail-other-merchandise' },
    ],
  },
  {
    label: 'Digital Products',
    items: [
      { label: 'Software as a service', value: 'digital-products-software-as-a-service' },
      { label: 'Apps', value: 'digital-products-apps' },
      { label: 'Books', value: 'digital-products-books' },
      { label: 'Music or other media', value: 'digital-products-music-or-other-media' },
      { label: 'Games', value: 'digital-products-games' },
      { label: 'Gaming Tokens', value: 'digital-products-gaming-tokens' },
      { label: 'Gaming skins', value: 'digital-products-gaming-skins' },
      { label: 'Blogs and written content', value: 'digital-products-blogs-and-written-content' },
      { label: 'Other digital goods', value: 'digital-products-other-digital-goods' },
    ],
  },
  {
    label: 'Food And Drink',
    items: [
      { label: 'Restaurants and nightlife', value: 'food-and-drink-restaurants-and-nightlife' },
      { label: 'Grocery stores', value: 'food-and-drink-grocery-stores' },
      { label: 'Caterers', value: 'food-and-drink-caterers' },
      { label: 'Other food and dining', value: 'food-and-drink-other-food-and-dining' },
    ],
  },
  {
    label: 'Professional Services',
    items: [
      { label: 'Consulting', value: 'professional-services-consulting' },
      { label: 'Printing and publishing', value: 'professional-services-printing-and-publishing' },
      { label: 'Attorneys and lawyers', value: 'professional-services-attorneys-and-lawyers' },
      { label: 'Bankruptcy services', value: 'professional-services-bankruptcy-services' },
      { label: 'Bail bonds', value: 'professional-services-bail-bonds' },
      { label: 'Accounting, auditing or tax prep', value: 'professional-services-accounting-auditing-or-tax-prep' },
      { label: 'Computer repair', value: 'professional-services-computer-repair' },
      { label: 'Testing laboratories', value: 'professional-services-testing-laboratories' },
      { label: 'Auto services', value: 'professional-services-auto-services' },
      { label: 'Car rentals', value: 'professional-services-car-rentals' },
      { label: 'Car sales', value: 'professional-services-car-sales' },
      { label: 'Lead generation', value: 'professional-services-lead-generation' },
      { label: 'Direct marketing', value: 'professional-services-direct-marketing' },
      { label: 'Utilities', value: 'professional-services-utilities' },
      { label: 'Government services', value: 'professional-services-government-services' },
      { label: 'Telemarketing', value: 'professional-services-telemarketing' },
      { label: 'Credit counselling or credit repair', value: 'professional-services-credit-counselling-or-credit-repair' },
      { label: 'Mortgage consulting services', value: 'professional-services-mortgage-consulting-services' },
      { label: 'Debt reduction services', value: 'professional-services-debt-reduction-services' },
      { label: 'Warranty services', value: 'professional-services-warranty-services' },
      { label: 'Other marketing services', value: 'professional-services-other-marketing-services' },
      { label: 'Other business services', value: 'professional-services-other-business-services' },
    ],
  },
  {
    label: 'Membership Organisations',
    items: [
      { label: 'Civic, fraternal or social associations', value: 'membership-organisations-civic-fraternal-or-social-associations' },
      { label: 'Charities or social services organisations', value: 'membership-organisations-charities-or-social-services-organisations' },
      { label: 'Religious organisations', value: 'membership-organisations-religious-organisations' },
      { label: 'Country clubs', value: 'membership-organisations-country-clubs' },
      { label: 'Political organisations', value: 'membership-organisations-political-organisations' },
      { label: 'Other membership organisation', value: 'membership-organisations-other-membership-organisation' },
    ],
  },
  {
    label: 'Personal Services',
    items: [
      { label: 'Photography studios', value: 'personal-services-photography-studios' },
      { label: 'Health and beauty spas', value: 'personal-services-health-and-beauty-spas' },
      { label: 'Salons or barbers', value: 'personal-services-salons-or-barbers' },
      { label: 'Landscaping services', value: 'personal-services-landscaping-services' },
      { label: 'Massage therapy practices', value: 'personal-services-massage-therapy-practices' },
      { label: 'Counselling services', value: 'personal-services-counselling-services' },
      { label: 'Health and wellness coaching', value: 'personal-services-health-and-wellness-coaching' },
      { label: 'Laundry or cleaning services', value: 'personal-services-laundry-or-cleaning-services' },
      { label: 'Dating services', value: 'personal-services-dating-services' },
      { label: 'Other personal services', value: 'personal-services-other-personal-services' },
    ],
  },
  {
    label: 'Transportation',
    items: [
      { label: 'Ridesharing', value: 'transportation-ridesharing' },
      { label: 'Taxis and limos', value: 'transportation-taxis-and-limos' },
      { label: 'Courier services', value: 'transportation-courier-services' },
      { label: 'Parking lots', value: 'transportation-parking-lots' },
      { label: 'Travel agencies', value: 'transportation-travel-agencies' },
      { label: 'Shipping or forwarding', value: 'transportation-shipping-or-forwarding' },
      { label: 'Commuter transportation', value: 'transportation-commuter-transportation' },
      { label: 'Cruise lines', value: 'transportation-cruise-lines' },
      { label: 'Airlines and air carriers', value: 'transportation-airlines-and-air-carriers' },
      { label: 'Other transportation services', value: 'transportation-other-transportation-services' },
    ],
  },
  {
    label: 'Travel and Lodging',
    items: [
      { label: 'Property rentals', value: 'travel-and-lodging-property-rentals' },
      { label: 'Hotels, inns or motels', value: 'travel-and-lodging-hotels-inns-or-motels' },
      { label: 'Timeshares', value: 'travel-and-lodging-timeshares' },
      { label: 'Other travel and lodging', value: 'travel-and-lodging-other-travel-and-lodging' },
    ],
  },
  {
    label: 'Medical Services',
    items: [
      { label: 'Medical devices', value: 'medical-services-medical-devices' },
      { label: 'Doctors and physicians', value: 'medical-services-doctors-and-physicians' },
      { label: 'Opticians and eyeglasses', value: 'medical-services-opticians-and-eyeglasses' },
      { label: 'Dentists and orthodontists', value: 'medical-services-dentists-and-orthodontists' },
      { label: 'Chiropractors', value: 'medical-services-chiropractors' },
      { label: 'Nursing or personal care facilities', value: 'medical-services-nursing-or-personal-care-facilities' },
      { label: 'Hospitals', value: 'medical-services-hospitals' },
      { label: 'Personal fundraising or crowdfunding', value: 'medical-services-personal-fundraising-or-crowdfunding' },
      { label: 'Mental health services', value: 'medical-services-mental-health-services' },
      { label: 'Assisted living', value: 'medical-services-assisted-living' },
      { label: 'Veterinary services', value: 'medical-services-veterinary-services' },
      { label: 'Medical organisations', value: 'medical-services-medical-organisations' },
      { label: 'Telemedicine and telehealth', value: 'medical-services-telemedicine-and-telehealth' },
      { label: 'Other medicinal services', value: 'medical-services-other-medicinal-services' },
    ],
  },
  {
    label: 'Education',
    items: [
      { label: 'Child care services', value: 'education-child-care-services' },
      { label: 'Colleges or universities', value: 'education-colleges-or-universities' },
      { label: 'Vocational schools or trade schools', value: 'education-vocational-schools-or-trade-schools' },
      { label: 'Elementary or secondary schools', value: 'education-elementary-or-secondary-schools' },
      { label: 'Forex trading courses', value: 'education-forex-trading-courses' },
      { label: 'Other educational services', value: 'education-other-educational-services' },
    ],
  },
  {
    label: 'Entertainment And Recreation',
    items: [
      { label: 'Event ticketing', value: 'entertainment-and-recreation-event-ticketing' },
      { label: 'Tourist attractions', value: 'entertainment-and-recreation-tourist-attractions' },
      { label: 'Recreational camps', value: 'entertainment-and-recreation-recreational-camps' },
      { label: 'Musicians, bands or orchestras', value: 'entertainment-and-recreation-musicians-bands-or-orchestras' },
      { label: 'Amusement parks, carnivals, or circuses', value: 'entertainment-and-recreation-amusement-parks-carnivals-or-circuses' },
      { label: 'Fortune tellers', value: 'entertainment-and-recreation-fortune-tellers' },
      { label: 'Cinemas', value: 'entertainment-and-recreation-cinemas' },
      { label: 'Betting or fantasy sports', value: 'entertainment-and-recreation-betting-or-fantasy-sports' },
      { label: 'Lotteries', value: 'entertainment-and-recreation-lotteries' },
      { label: 'Sports forecasting or prediction services', value: 'entertainment-and-recreation-sports-forecasting-or-prediction-services' },
      { label: 'Online gambling', value: 'entertainment-and-recreation-online-gambling' },
      { label: 'Other entertainment and recreation', value: 'entertainment-and-recreation-other-entertainment-and-recreation' },
    ],
  },
  {
    label: 'Building Services',
    items: [
      { label: 'General contractors', value: 'building-services-general-contractors' },
      { label: 'Electrical contractors', value: 'building-services-electrical-contractors' },
      { label: 'Carpentry contractors', value: 'building-services-carpentry-contractors' },
      { label: 'Special trade contractors', value: 'building-services-special-trade-contractors' },
      { label: 'Telecom services', value: 'building-services-telecom-services' },
      { label: 'Telecom equipment', value: 'building-services-telecom-equipment' },
      { label: 'A/C and heating contractors', value: 'building-services-a-c-and-heating-contractors' },
      { label: 'Other building services', value: 'building-services-other-building-services' },
    ],
  },
  {
    label: 'Financial Services',
    items: [
      { label: 'Insurance', value: 'financial-services-insurance' },
      { label: 'Security brokers or dealers', value: 'financial-services-security-brokers-or-dealers' },
      { label: 'Money orders', value: 'financial-services-money-orders' },
      { label: 'Currency exchange', value: 'financial-services-currency-exchange' },
      { label: 'Wire transfers', value: 'financial-services-wire-transfers' },
      { label: 'Cheque cashing', value: 'financial-services-cheque-cashing' },
      { label: 'Loans and lending', value: 'financial-services-loans-and-lending' },
      { label: 'Collections agencies', value: 'financial-services-collections-agencies' },
      { label: 'Money services or transmission', value: 'financial-services-money-services-or-transmission' },
      { label: 'Investment services', value: 'financial-services-investment-services' },
      { label: 'Virtual currencies', value: 'financial-services-virtual-currencies' },
      { label: 'Digital wallets', value: 'financial-services-digital-wallets' },
      { label: 'Cryptocurrencies', value: 'financial-services-cryptocurrencies' },
      { label: 'Forex / FX trading', value: 'financial-services-forex-fx-trading' },
      { label: 'Other financial institutions', value: 'financial-services-other-financial-institutions' },
      { label: 'Financial information and research', value: 'financial-services-financial-information-and-research' },
    ],
  },
  {
    label: 'Regulated And Age-Restricted Products',
    items: [
      { label: 'Pharmacies or pharmaceuticals', value: 'regulated-and-age-restricted-products-pharmacies-or-pharmaceuticals' },
      { label: 'Tobacco or cigars', value: 'regulated-and-age-restricted-products-tobacco-or-cigars' },
      { label: 'Adult content or services', value: 'regulated-and-age-restricted-products-adult-content-or-services' },
      { label: 'Webcam streaming platform', value: 'regulated-and-age-restricted-products-webcam-streaming-platform' },
      { label: 'Escorting', value: 'regulated-and-age-restricted-products-escorting' },
      { label: 'Vapes, e-cigarettes, e-juice or related products', value: 'regulated-and-age-restricted-products-vapes-e-cigarettes,e-juice-or-related-products' },
      { label: 'Weapons or munitions', value: 'regulated-and-age-restricted-products-weapons-or-munitions' },
      { label: 'Supplement or nutraceutical', value: 'regulated-and-age-restricted-products-supplement-or-nutraceuticals' },
      { label: 'Marijuana dispensaries', value: 'regulated-and-age-restricted-products-marijuana-dispensaries' },
      { label: 'Marijuana-related products', value: 'regulated-and-age-restricted-products-marijuana-related-products' },
      { label: 'CBD', value: 'regulated-and-age-restricted-products-cbd' },
      { label: 'Accessories for tobacco and marijuana', value: 'regulated-and-age-restricted-products-accessories-for-tobacco-and-marijuana' },
      { label: 'Alcohol', value: 'regulated-and-age-restricted-products-alcohol' },
    ],
  },
];